//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VESHTER.SiteDetailsWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://veshter.com/webservices/sitedetails/", ConfigurationName="SiteDetailsWS.SiteDetails")]
    internal interface SiteDetails {
        
        // CODEGEN: Parameter 'balance' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/sitedetails/GetCurrentBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="balance")]
        VESHTER.SiteDetailsWS.GetCurrentBalanceResponse GetCurrentBalance(VESHTER.SiteDetailsWS.GetCurrentBalanceRequest request);
        
        // CODEGEN: Parameter 'services' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/sitedetails/GetCurrentContract", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="services")]
        VESHTER.SiteDetailsWS.GetCurrentContractResponse GetCurrentContract(VESHTER.SiteDetailsWS.GetCurrentContractRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrentBalance", WrapperNamespace="http://veshter.com/webservices/sitedetails/", IsWrapped=true)]
    internal partial class GetCurrentBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/sitedetails/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/sitedetails/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public GetCurrentBalanceRequest() {
        }
        
        public GetCurrentBalanceRequest(string resource, string token) {
            this.resource = resource;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrentBalanceResponse", WrapperNamespace="http://veshter.com/webservices/sitedetails/", IsWrapped=true)]
    internal partial class GetCurrentBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/sitedetails/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float balance;
        
        public GetCurrentBalanceResponse() {
        }
        
        public GetCurrentBalanceResponse(float balance) {
            this.balance = balance;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://veshter.com/webservices/sitedetails/")]
    public partial class Service : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private float quantityField;
        
        private string aboutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public float quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string about {
            get {
                return this.aboutField;
            }
            set {
                this.aboutField = value;
                this.RaisePropertyChanged("about");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrentContract", WrapperNamespace="http://veshter.com/webservices/sitedetails/", IsWrapped=true)]
    internal partial class GetCurrentContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/sitedetails/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/sitedetails/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public GetCurrentContractRequest() {
        }
        
        public GetCurrentContractRequest(string resource, string token) {
            this.resource = resource;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrentContractResponse", WrapperNamespace="http://veshter.com/webservices/sitedetails/", IsWrapped=true)]
    internal partial class GetCurrentContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/sitedetails/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("services", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Service[] services;
        
        public GetCurrentContractResponse() {
        }
        
        public GetCurrentContractResponse(Service[] services) {
            this.services = services;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface SiteDetailsChannel : VESHTER.SiteDetailsWS.SiteDetails, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class SiteDetailsClient : System.ServiceModel.ClientBase<VESHTER.SiteDetailsWS.SiteDetails>, VESHTER.SiteDetailsWS.SiteDetails {
        
        public SiteDetailsClient() {
        }
        
        public SiteDetailsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiteDetailsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteDetailsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteDetailsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.SiteDetailsWS.GetCurrentBalanceResponse VESHTER.SiteDetailsWS.SiteDetails.GetCurrentBalance(VESHTER.SiteDetailsWS.GetCurrentBalanceRequest request) {
            return base.Channel.GetCurrentBalance(request);
        }
        
        public float GetCurrentBalance(string resource, string token) {
            VESHTER.SiteDetailsWS.GetCurrentBalanceRequest inValue = new VESHTER.SiteDetailsWS.GetCurrentBalanceRequest();
            inValue.resource = resource;
            inValue.token = token;
            VESHTER.SiteDetailsWS.GetCurrentBalanceResponse retVal = ((VESHTER.SiteDetailsWS.SiteDetails)(this)).GetCurrentBalance(inValue);
            return retVal.balance;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.SiteDetailsWS.GetCurrentContractResponse VESHTER.SiteDetailsWS.SiteDetails.GetCurrentContract(VESHTER.SiteDetailsWS.GetCurrentContractRequest request) {
            return base.Channel.GetCurrentContract(request);
        }
        
        public Service[] GetCurrentContract(string resource, string token) {
            VESHTER.SiteDetailsWS.GetCurrentContractRequest inValue = new VESHTER.SiteDetailsWS.GetCurrentContractRequest();
            inValue.resource = resource;
            inValue.token = token;
            VESHTER.SiteDetailsWS.GetCurrentContractResponse retVal = ((VESHTER.SiteDetailsWS.SiteDetails)(this)).GetCurrentContract(inValue);
            return retVal.services;
        }
    }
}
