//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VESHTER.SupportTicketsWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://veshter.com/webservices/supporttickets/", ConfigurationName="SupportTicketsWS.SupportTickets")]
    internal interface SupportTickets {
        
        // CODEGEN: Parameter 'ticket' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/supporttickets/OpenTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ticket")]
        VESHTER.SupportTicketsWS.OpenTicketResponse OpenTicket(VESHTER.SupportTicketsWS.OpenTicketRequest request);
        
        // CODEGEN: Parameter 'isClosed' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/supporttickets/CloseTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isClosed")]
        VESHTER.SupportTicketsWS.CloseTicketResponse CloseTicket(VESHTER.SupportTicketsWS.CloseTicketRequest request);
        
        // CODEGEN: Parameter 'isReopened' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/supporttickets/ReopenTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isReopened")]
        VESHTER.SupportTicketsWS.ReopenTicketResponse ReopenTicket(VESHTER.SupportTicketsWS.ReopenTicketRequest request);
        
        // CODEGEN: Parameter 'isAdded' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/supporttickets/AddTicketNote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isAdded")]
        VESHTER.SupportTicketsWS.AddTicketNoteResponse AddTicketNote(VESHTER.SupportTicketsWS.AddTicketNoteRequest request);
        
        // CODEGEN: Parameter 'tickets' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/supporttickets/GetAllTickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="tickets")]
        VESHTER.SupportTicketsWS.GetAllTicketsResponse GetAllTickets(VESHTER.SupportTicketsWS.GetAllTicketsRequest request);
        
        // CODEGEN: Parameter 'tickets' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/supporttickets/GetAllOpenTickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="tickets")]
        VESHTER.SupportTicketsWS.GetAllOpenTicketsResponse GetAllOpenTickets(VESHTER.SupportTicketsWS.GetAllOpenTicketsRequest request);
        
        // CODEGEN: Parameter 'details' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/supporttickets/GetTicketDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="details")]
        VESHTER.SupportTicketsWS.GetTicketDetailsResponse GetTicketDetails(VESHTER.SupportTicketsWS.GetTicketDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://veshter.com/webservices/supporttickets/")]
    public partial class SupportTicket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string guidField;
        
        private string nameField;
        
        private int priorityField;
        
        private SupportTicketNote[] notesField;
        
        private string statusField;
        
        private float lastOpenField;
        
        private float lastUpdateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public SupportTicketNote[] notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public float lastOpen {
            get {
                return this.lastOpenField;
            }
            set {
                this.lastOpenField = value;
                this.RaisePropertyChanged("lastOpen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public float lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
                this.RaisePropertyChanged("lastUpdate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://veshter.com/webservices/supporttickets/")]
    public partial class SupportTicketNote : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string guidField;
        
        private string aboutField;
        
        private string authorField;
        
        private string lastUpdateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string about {
            get {
                return this.aboutField;
            }
            set {
                this.aboutField = value;
                this.RaisePropertyChanged("about");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("author");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
                this.RaisePropertyChanged("lastUpdate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenTicket", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class OpenTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VESHTER.SupportTicketsWS.SupportTicket details;
        
        public OpenTicketRequest() {
        }
        
        public OpenTicketRequest(string resource, string token, VESHTER.SupportTicketsWS.SupportTicket details) {
            this.resource = resource;
            this.token = token;
            this.details = details;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenTicketResponse", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class OpenTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ticket;
        
        public OpenTicketResponse() {
        }
        
        public OpenTicketResponse(string ticket) {
            this.ticket = ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CloseTicket", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class CloseTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VESHTER.SupportTicketsWS.SupportTicketNote note;
        
        public CloseTicketRequest() {
        }
        
        public CloseTicketRequest(string resource, string token, string ticket, VESHTER.SupportTicketsWS.SupportTicketNote note) {
            this.resource = resource;
            this.token = token;
            this.ticket = ticket;
            this.note = note;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CloseTicketResponse", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class CloseTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isClosed;
        
        public CloseTicketResponse() {
        }
        
        public CloseTicketResponse(bool isClosed) {
            this.isClosed = isClosed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReopenTicket", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class ReopenTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VESHTER.SupportTicketsWS.SupportTicketNote note;
        
        public ReopenTicketRequest() {
        }
        
        public ReopenTicketRequest(string resource, string token, string ticket, VESHTER.SupportTicketsWS.SupportTicketNote note) {
            this.resource = resource;
            this.token = token;
            this.ticket = ticket;
            this.note = note;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReopenTicketResponse", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class ReopenTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isReopened;
        
        public ReopenTicketResponse() {
        }
        
        public ReopenTicketResponse(bool isReopened) {
            this.isReopened = isReopened;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddTicketNote", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class AddTicketNoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VESHTER.SupportTicketsWS.SupportTicketNote note;
        
        public AddTicketNoteRequest() {
        }
        
        public AddTicketNoteRequest(string resource, string token, string ticket, VESHTER.SupportTicketsWS.SupportTicketNote note) {
            this.resource = resource;
            this.token = token;
            this.ticket = ticket;
            this.note = note;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddTicketNoteResponse", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class AddTicketNoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isAdded;
        
        public AddTicketNoteResponse() {
        }
        
        public AddTicketNoteResponse(bool isAdded) {
            this.isAdded = isAdded;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllTickets", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class GetAllTicketsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public GetAllTicketsRequest() {
        }
        
        public GetAllTicketsRequest(string resource, string token) {
            this.resource = resource;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllTicketsResponse", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class GetAllTicketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("tickets", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SupportTicket[] tickets;
        
        public GetAllTicketsResponse() {
        }
        
        public GetAllTicketsResponse(SupportTicket[] tickets) {
            this.tickets = tickets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllOpenTickets", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class GetAllOpenTicketsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public GetAllOpenTicketsRequest() {
        }
        
        public GetAllOpenTicketsRequest(string resource, string token) {
            this.resource = resource;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllOpenTicketsResponse", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class GetAllOpenTicketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("tickets", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SupportTicket[] tickets;
        
        public GetAllOpenTicketsResponse() {
        }
        
        public GetAllOpenTicketsResponse(SupportTicket[] tickets) {
            this.tickets = tickets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTicketDetails", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class GetTicketDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ticket;
        
        public GetTicketDetailsRequest() {
        }
        
        public GetTicketDetailsRequest(string resource, string token, string ticket) {
            this.resource = resource;
            this.token = token;
            this.ticket = ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTicketDetailsResponse", WrapperNamespace="http://veshter.com/webservices/supporttickets/", IsWrapped=true)]
    internal partial class GetTicketDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/supporttickets/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VESHTER.SupportTicketsWS.SupportTicket details;
        
        public GetTicketDetailsResponse() {
        }
        
        public GetTicketDetailsResponse(VESHTER.SupportTicketsWS.SupportTicket details) {
            this.details = details;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface SupportTicketsChannel : VESHTER.SupportTicketsWS.SupportTickets, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class SupportTicketsClient : System.ServiceModel.ClientBase<VESHTER.SupportTicketsWS.SupportTickets>, VESHTER.SupportTicketsWS.SupportTickets {
        
        public SupportTicketsClient() {
        }
        
        public SupportTicketsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupportTicketsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupportTicketsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupportTicketsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.SupportTicketsWS.OpenTicketResponse VESHTER.SupportTicketsWS.SupportTickets.OpenTicket(VESHTER.SupportTicketsWS.OpenTicketRequest request) {
            return base.Channel.OpenTicket(request);
        }
        
        public string OpenTicket(string resource, string token, VESHTER.SupportTicketsWS.SupportTicket details) {
            VESHTER.SupportTicketsWS.OpenTicketRequest inValue = new VESHTER.SupportTicketsWS.OpenTicketRequest();
            inValue.resource = resource;
            inValue.token = token;
            inValue.details = details;
            VESHTER.SupportTicketsWS.OpenTicketResponse retVal = ((VESHTER.SupportTicketsWS.SupportTickets)(this)).OpenTicket(inValue);
            return retVal.ticket;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.SupportTicketsWS.CloseTicketResponse VESHTER.SupportTicketsWS.SupportTickets.CloseTicket(VESHTER.SupportTicketsWS.CloseTicketRequest request) {
            return base.Channel.CloseTicket(request);
        }
        
        public bool CloseTicket(string resource, string token, string ticket, VESHTER.SupportTicketsWS.SupportTicketNote note) {
            VESHTER.SupportTicketsWS.CloseTicketRequest inValue = new VESHTER.SupportTicketsWS.CloseTicketRequest();
            inValue.resource = resource;
            inValue.token = token;
            inValue.ticket = ticket;
            inValue.note = note;
            VESHTER.SupportTicketsWS.CloseTicketResponse retVal = ((VESHTER.SupportTicketsWS.SupportTickets)(this)).CloseTicket(inValue);
            return retVal.isClosed;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.SupportTicketsWS.ReopenTicketResponse VESHTER.SupportTicketsWS.SupportTickets.ReopenTicket(VESHTER.SupportTicketsWS.ReopenTicketRequest request) {
            return base.Channel.ReopenTicket(request);
        }
        
        public bool ReopenTicket(string resource, string token, string ticket, VESHTER.SupportTicketsWS.SupportTicketNote note) {
            VESHTER.SupportTicketsWS.ReopenTicketRequest inValue = new VESHTER.SupportTicketsWS.ReopenTicketRequest();
            inValue.resource = resource;
            inValue.token = token;
            inValue.ticket = ticket;
            inValue.note = note;
            VESHTER.SupportTicketsWS.ReopenTicketResponse retVal = ((VESHTER.SupportTicketsWS.SupportTickets)(this)).ReopenTicket(inValue);
            return retVal.isReopened;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.SupportTicketsWS.AddTicketNoteResponse VESHTER.SupportTicketsWS.SupportTickets.AddTicketNote(VESHTER.SupportTicketsWS.AddTicketNoteRequest request) {
            return base.Channel.AddTicketNote(request);
        }
        
        public bool AddTicketNote(string resource, string token, string ticket, VESHTER.SupportTicketsWS.SupportTicketNote note) {
            VESHTER.SupportTicketsWS.AddTicketNoteRequest inValue = new VESHTER.SupportTicketsWS.AddTicketNoteRequest();
            inValue.resource = resource;
            inValue.token = token;
            inValue.ticket = ticket;
            inValue.note = note;
            VESHTER.SupportTicketsWS.AddTicketNoteResponse retVal = ((VESHTER.SupportTicketsWS.SupportTickets)(this)).AddTicketNote(inValue);
            return retVal.isAdded;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.SupportTicketsWS.GetAllTicketsResponse VESHTER.SupportTicketsWS.SupportTickets.GetAllTickets(VESHTER.SupportTicketsWS.GetAllTicketsRequest request) {
            return base.Channel.GetAllTickets(request);
        }
        
        public SupportTicket[] GetAllTickets(string resource, string token) {
            VESHTER.SupportTicketsWS.GetAllTicketsRequest inValue = new VESHTER.SupportTicketsWS.GetAllTicketsRequest();
            inValue.resource = resource;
            inValue.token = token;
            VESHTER.SupportTicketsWS.GetAllTicketsResponse retVal = ((VESHTER.SupportTicketsWS.SupportTickets)(this)).GetAllTickets(inValue);
            return retVal.tickets;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.SupportTicketsWS.GetAllOpenTicketsResponse VESHTER.SupportTicketsWS.SupportTickets.GetAllOpenTickets(VESHTER.SupportTicketsWS.GetAllOpenTicketsRequest request) {
            return base.Channel.GetAllOpenTickets(request);
        }
        
        public SupportTicket[] GetAllOpenTickets(string resource, string token) {
            VESHTER.SupportTicketsWS.GetAllOpenTicketsRequest inValue = new VESHTER.SupportTicketsWS.GetAllOpenTicketsRequest();
            inValue.resource = resource;
            inValue.token = token;
            VESHTER.SupportTicketsWS.GetAllOpenTicketsResponse retVal = ((VESHTER.SupportTicketsWS.SupportTickets)(this)).GetAllOpenTickets(inValue);
            return retVal.tickets;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.SupportTicketsWS.GetTicketDetailsResponse VESHTER.SupportTicketsWS.SupportTickets.GetTicketDetails(VESHTER.SupportTicketsWS.GetTicketDetailsRequest request) {
            return base.Channel.GetTicketDetails(request);
        }
        
        public VESHTER.SupportTicketsWS.SupportTicket GetTicketDetails(string resource, string token, string ticket) {
            VESHTER.SupportTicketsWS.GetTicketDetailsRequest inValue = new VESHTER.SupportTicketsWS.GetTicketDetailsRequest();
            inValue.resource = resource;
            inValue.token = token;
            inValue.ticket = ticket;
            VESHTER.SupportTicketsWS.GetTicketDetailsResponse retVal = ((VESHTER.SupportTicketsWS.SupportTickets)(this)).GetTicketDetails(inValue);
            return retVal.details;
        }
    }
}
