//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VESHTER.ScriptsWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://veshter.com/webservices/scripts/", ConfigurationName="ScriptsWS.Scripts")]
    public interface Scripts {
        
        // CODEGEN: Parameter 'scripts' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/scripts/GetLatestScripts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="scripts")]
        VESHTER.ScriptsWS.GetLatestScriptsResponse GetLatestScripts(VESHTER.ScriptsWS.GetLatestScriptsRequest request);
        
        // CODEGEN: Parameter 'details' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/scripts/GetScriptDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="details")]
        VESHTER.ScriptsWS.GetScriptDetailsResponse GetScriptDetails(VESHTER.ScriptsWS.GetScriptDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://veshter.com/webservices/scripts/")]
    public partial class Script : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string folderField;
        
        private string filenameField;
        
        private string sourceField;
        
        private float versionField;
        
        private string changelogField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
                this.RaisePropertyChanged("folder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public float version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string changelog {
            get {
                return this.changelogField;
            }
            set {
                this.changelogField = value;
                this.RaisePropertyChanged("changelog");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestScripts", WrapperNamespace="http://veshter.com/webservices/scripts/", IsWrapped=true)]
    public partial class GetLatestScriptsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/scripts/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/scripts/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public GetLatestScriptsRequest() {
        }
        
        public GetLatestScriptsRequest(string resource, string token) {
            this.resource = resource;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLatestScriptsResponse", WrapperNamespace="http://veshter.com/webservices/scripts/", IsWrapped=true)]
    public partial class GetLatestScriptsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/scripts/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("scripts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Script[] scripts;
        
        public GetLatestScriptsResponse() {
        }
        
        public GetLatestScriptsResponse(Script[] scripts) {
            this.scripts = scripts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScriptDetails", WrapperNamespace="http://veshter.com/webservices/scripts/", IsWrapped=true)]
    public partial class GetScriptDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/scripts/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/scripts/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/scripts/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string folder;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/scripts/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filename;
        
        public GetScriptDetailsRequest() {
        }
        
        public GetScriptDetailsRequest(string resource, string token, string folder, string filename) {
            this.resource = resource;
            this.token = token;
            this.folder = folder;
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScriptDetailsResponse", WrapperNamespace="http://veshter.com/webservices/scripts/", IsWrapped=true)]
    public partial class GetScriptDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://veshter.com/webservices/scripts/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VESHTER.ScriptsWS.Script details;
        
        public GetScriptDetailsResponse() {
        }
        
        public GetScriptDetailsResponse(VESHTER.ScriptsWS.Script details) {
            this.details = details;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ScriptsChannel : VESHTER.ScriptsWS.Scripts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScriptsClient : System.ServiceModel.ClientBase<VESHTER.ScriptsWS.Scripts>, VESHTER.ScriptsWS.Scripts {
        
        public ScriptsClient() {
        }
        
        public ScriptsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScriptsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScriptsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScriptsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.ScriptsWS.GetLatestScriptsResponse VESHTER.ScriptsWS.Scripts.GetLatestScripts(VESHTER.ScriptsWS.GetLatestScriptsRequest request) {
            return base.Channel.GetLatestScripts(request);
        }
        
        public Script[] GetLatestScripts(string resource, string token) {
            VESHTER.ScriptsWS.GetLatestScriptsRequest inValue = new VESHTER.ScriptsWS.GetLatestScriptsRequest();
            inValue.resource = resource;
            inValue.token = token;
            VESHTER.ScriptsWS.GetLatestScriptsResponse retVal = ((VESHTER.ScriptsWS.Scripts)(this)).GetLatestScripts(inValue);
            return retVal.scripts;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.ScriptsWS.GetScriptDetailsResponse VESHTER.ScriptsWS.Scripts.GetScriptDetails(VESHTER.ScriptsWS.GetScriptDetailsRequest request) {
            return base.Channel.GetScriptDetails(request);
        }
        
        public VESHTER.ScriptsWS.Script GetScriptDetails(string resource, string token, string folder, string filename) {
            VESHTER.ScriptsWS.GetScriptDetailsRequest inValue = new VESHTER.ScriptsWS.GetScriptDetailsRequest();
            inValue.resource = resource;
            inValue.token = token;
            inValue.folder = folder;
            inValue.filename = filename;
            VESHTER.ScriptsWS.GetScriptDetailsResponse retVal = ((VESHTER.ScriptsWS.Scripts)(this)).GetScriptDetails(inValue);
            return retVal.details;
        }
    }
}
