//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VESHTER.TokensWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://veshter.com/webservices/tokens/", ConfigurationName="TokensWS.Tokens")]
    internal interface Tokens {
        
        // CODEGEN: Generating message contract since element name resource from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/tokens/GenerateToken", ReplyAction="*")]
        VESHTER.TokensWS.GenerateTokenResponse GenerateToken(VESHTER.TokensWS.GenerateTokenRequest request);
        
        // CODEGEN: Generating message contract since element name resource from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/tokens/ValidateToken", ReplyAction="*")]
        VESHTER.TokensWS.ValidateTokenResponse ValidateToken(VESHTER.TokensWS.ValidateTokenRequest request);
        
        // CODEGEN: Generating message contract since element name internalToken from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://veshter.com/webservices/tokens/InvalidateToken", ReplyAction="*")]
        VESHTER.TokensWS.InvalidateTokenResponse InvalidateToken(VESHTER.TokensWS.InvalidateTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GenerateTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateToken", Namespace="http://veshter.com/webservices/tokens/", Order=0)]
        public VESHTER.TokensWS.GenerateTokenRequestBody Body;
        
        public GenerateTokenRequest() {
        }
        
        public GenerateTokenRequest(VESHTER.TokensWS.GenerateTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class GenerateTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resource;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string externalToken;
        
        public GenerateTokenRequestBody() {
        }
        
        public GenerateTokenRequestBody(string resource, string externalToken) {
            this.resource = resource;
            this.externalToken = externalToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GenerateTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateTokenResponse", Namespace="http://veshter.com/webservices/tokens/", Order=0)]
        public VESHTER.TokensWS.GenerateTokenResponseBody Body;
        
        public GenerateTokenResponse() {
        }
        
        public GenerateTokenResponse(VESHTER.TokensWS.GenerateTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class GenerateTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string internalToken;
        
        public GenerateTokenResponseBody() {
        }
        
        public GenerateTokenResponseBody(string internalToken) {
            this.internalToken = internalToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ValidateTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateToken", Namespace="http://veshter.com/webservices/tokens/", Order=0)]
        public VESHTER.TokensWS.ValidateTokenRequestBody Body;
        
        public ValidateTokenRequest() {
        }
        
        public ValidateTokenRequest(VESHTER.TokensWS.ValidateTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class ValidateTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resource;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string internalToken;
        
        public ValidateTokenRequestBody() {
        }
        
        public ValidateTokenRequestBody(string resource, string internalToken) {
            this.resource = resource;
            this.internalToken = internalToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ValidateTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateTokenResponse", Namespace="http://veshter.com/webservices/tokens/", Order=0)]
        public VESHTER.TokensWS.ValidateTokenResponseBody Body;
        
        public ValidateTokenResponse() {
        }
        
        public ValidateTokenResponse(VESHTER.TokensWS.ValidateTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class ValidateTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isValid;
        
        public ValidateTokenResponseBody() {
        }
        
        public ValidateTokenResponseBody(bool isValid) {
            this.isValid = isValid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class InvalidateTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvalidateToken", Namespace="http://veshter.com/webservices/tokens/", Order=0)]
        public VESHTER.TokensWS.InvalidateTokenRequestBody Body;
        
        public InvalidateTokenRequest() {
        }
        
        public InvalidateTokenRequest(VESHTER.TokensWS.InvalidateTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class InvalidateTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string internalToken;
        
        public InvalidateTokenRequestBody() {
        }
        
        public InvalidateTokenRequestBody(string internalToken) {
            this.internalToken = internalToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class InvalidateTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvalidateTokenResponse", Namespace="http://veshter.com/webservices/tokens/", Order=0)]
        public VESHTER.TokensWS.InvalidateTokenResponseBody Body;
        
        public InvalidateTokenResponse() {
        }
        
        public InvalidateTokenResponse(VESHTER.TokensWS.InvalidateTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class InvalidateTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isInvalid;
        
        public InvalidateTokenResponseBody() {
        }
        
        public InvalidateTokenResponseBody(bool isInvalid) {
            this.isInvalid = isInvalid;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface TokensChannel : VESHTER.TokensWS.Tokens, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class TokensClient : System.ServiceModel.ClientBase<VESHTER.TokensWS.Tokens>, VESHTER.TokensWS.Tokens {
        
        public TokensClient() {
        }
        
        public TokensClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokensClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokensClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokensClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.TokensWS.GenerateTokenResponse VESHTER.TokensWS.Tokens.GenerateToken(VESHTER.TokensWS.GenerateTokenRequest request) {
            return base.Channel.GenerateToken(request);
        }
        
        public string GenerateToken(string resource, string externalToken) {
            VESHTER.TokensWS.GenerateTokenRequest inValue = new VESHTER.TokensWS.GenerateTokenRequest();
            inValue.Body = new VESHTER.TokensWS.GenerateTokenRequestBody();
            inValue.Body.resource = resource;
            inValue.Body.externalToken = externalToken;
            VESHTER.TokensWS.GenerateTokenResponse retVal = ((VESHTER.TokensWS.Tokens)(this)).GenerateToken(inValue);
            return retVal.Body.internalToken;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.TokensWS.ValidateTokenResponse VESHTER.TokensWS.Tokens.ValidateToken(VESHTER.TokensWS.ValidateTokenRequest request) {
            return base.Channel.ValidateToken(request);
        }
        
        public bool ValidateToken(string resource, string internalToken) {
            VESHTER.TokensWS.ValidateTokenRequest inValue = new VESHTER.TokensWS.ValidateTokenRequest();
            inValue.Body = new VESHTER.TokensWS.ValidateTokenRequestBody();
            inValue.Body.resource = resource;
            inValue.Body.internalToken = internalToken;
            VESHTER.TokensWS.ValidateTokenResponse retVal = ((VESHTER.TokensWS.Tokens)(this)).ValidateToken(inValue);
            return retVal.Body.isValid;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VESHTER.TokensWS.InvalidateTokenResponse VESHTER.TokensWS.Tokens.InvalidateToken(VESHTER.TokensWS.InvalidateTokenRequest request) {
            return base.Channel.InvalidateToken(request);
        }
        
        public bool InvalidateToken(string internalToken) {
            VESHTER.TokensWS.InvalidateTokenRequest inValue = new VESHTER.TokensWS.InvalidateTokenRequest();
            inValue.Body = new VESHTER.TokensWS.InvalidateTokenRequestBody();
            inValue.Body.internalToken = internalToken;
            VESHTER.TokensWS.InvalidateTokenResponse retVal = ((VESHTER.TokensWS.Tokens)(this)).InvalidateToken(inValue);
            return retVal.Body.isInvalid;
        }
    }
}
